<a href="https://colab.research.google.com/github/Mahathi06/Complete-Python-3-Bootcamp/blob/master/dataanalysis_numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("Hello world")

Hello world


In [4]:
import numpy as np

In [7]:
my_list=[1,2,3,4,5]
print(my_list)

[1, 2, 3, 4, 5]


In [8]:
for i in my_list:
  print(i+5)


6
7
8
9
10


In [10]:
numpy_arr=np.array([1,2,3,4,5])
print(numpy_arr)

[1 2 3 4 5]


In [12]:
type(numpy_arr)

numpy.ndarray

In [13]:
type(my_list)

list

In [15]:
numpy_arr+5

array([ 6,  7,  8,  9, 10])

In [16]:
numpy_arr.size

5

In [18]:
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr2=np.arange(20,38)
print(arr2[-1])

37


In [26]:
arr2[arr2>25]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])

In [27]:
#nps
!gdown 1PQhT_-kTg1JhTKFq0U-5MzQ4gARu-V3a

Downloading...
From: https://drive.google.com/uc?id=1PQhT_-kTg1JhTKFq0U-5MzQ4gARu-V3a
To: /content/survey_large.txt
100% 21.8M/21.8M [00:00<00:00, 177MB/s]


In [29]:
scores=np.loadtxt('survey_large.txt',dtype='int')
scores

array([ 7, 10,  5, ...,  9,  5,  9])

In [30]:
scores.size

10000000

In [31]:
scores.min()

1

In [34]:
scores.max()

10

In [37]:
scores.mean()

7.250214

In [38]:
detractors=scores[scores<7]
print(detractors)

[5 4 4 ... 5 4 5]


In [39]:
promoters=scores[scores>8]
print(promoters)


[10  9  9 ... 10  9  9]


In [40]:
detractors.size

2844902

In [41]:
promoters.size

5218510

In [44]:
survey=100*(promoters.size-detractors.size)/scores.size
print(survey)

23.73608


In [45]:
import pandas as pd

In [46]:
!wget "https://drive.google.com/uc?export=download&id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_" -O data.csv

--2023-07-02 13:28:33--  https://drive.google.com/uc?export=download&id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_
Resolving drive.google.com (drive.google.com)... 142.250.97.102, 142.250.97.113, 142.250.97.100, ...
Connecting to drive.google.com (drive.google.com)|142.250.97.102|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-0s-68-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/1k6ap7ufu8mcvhs8dkpvmqj0m56tf8i4/1688304450000/14302370361230157278/*/1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_?e=download&uuid=76112bc7-e21f-4c42-a953-5a112bdc4cd8 [following]
--2023-07-02 13:28:33--  https://doc-0s-68-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/1k6ap7ufu8mcvhs8dkpvmqj0m56tf8i4/1688304450000/14302370361230157278/*/1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_?e=download&uuid=76112bc7-e21f-4c42-a953-5a112bdc4cd8
Resolving doc-0s-68-docs.googleusercontent.com (doc-0s-68-docs.googleusercontent.com)... 142.251.162.132, 2607

In [47]:
df = pd.read_csv('data.csv')

In [49]:
df.head()

country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [50]:
df.size

10224

In [51]:
df.shape

(1704, 6)

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   country     1704 non-null   object 
 1   year        1704 non-null   int64  
 2   population  1704 non-null   int64  
 3   continent   1704 non-null   object 
 4   life_exp    1704 non-null   float64
 5   gdp_cap     1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB


In [54]:
df.describe()

year    population     life_exp        gdp_cap
count  1704.00000  1.704000e+03  1704.000000    1704.000000
mean   1979.50000  2.960121e+07    59.474439    7215.327081
std      17.26533  1.061579e+08    12.917107    9857.454543
min    1952.00000  6.001100e+04    23.599000     241.165876
25%    1965.75000  2.793664e+06    48.198000    1202.060309
50%    1979.50000  7.023596e+06    60.712500    3531.846988
75%    1993.25000  1.958522e+07    70.845500    9325.462346
max    2007.00000  1.318683e+09    82.603000  113523.132900

In [58]:
df_2007=df[df['year']==2007]
df_2007

country  year  population continent  life_exp       gdp_cap
11           Afghanistan  2007    31889923      Asia    43.828    974.580338
23               Albania  2007     3600523    Europe    76.423   5937.029526
35               Algeria  2007    33333216    Africa    72.301   6223.367465
47                Angola  2007    12420476    Africa    42.731   4797.231267
59             Argentina  2007    40301927  Americas    75.320  12779.379640
...                  ...   ...         ...       ...       ...           ...
1655             Vietnam  2007    85262356      Asia    74.249   2441.576404
1667  West Bank and Gaza  2007     4018332      Asia    73.422   3025.349798
1679         Yemen, Rep.  2007    22211743      Asia    62.698   2280.769906
1691              Zambia  2007    11746035    Africa    42.384   1271.211593
1703            Zimbabwe  2007    12311143    Africa    43.487    469.709298

[142 rows x 6 columns]

In [59]:
df_2007.head()

country  year  population continent  life_exp       gdp_cap
11  Afghanistan  2007    31889923      Asia    43.828    974.580338
23      Albania  2007     3600523    Europe    76.423   5937.029526
35      Algeria  2007    33333216    Africa    72.301   6223.367465
47       Angola  2007    12420476    Africa    42.731   4797.231267
59    Argentina  2007    40301927  Americas    75.320  12779.379640

In [61]:
le_min=df_2007['life_exp'].min()

In [62]:
df_2007[df_2007['life_exp']==le_min]

country  year  population continent  life_exp      gdp_cap
1463  Swaziland  2007     1133066    Africa    39.613  4513.480643

In [63]:
le_max=df_2007['gdp_cap'].max()

In [64]:
df_2007[df_2007['gdp_cap']==le_max]

country  year  population continent  life_exp      gdp_cap
1151  Norway  2007     4627926    Europe    80.196  49357.19017